// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFMkwiEZX8PSBPn-qnF3vwAvhAYhwFoA',
    appId: '1:147056837699:web:14c16834d48536208d40f6',
    messagingSenderId: '147056837699',
    projectId: 'chatapp-cc76c',
    authDomain: 'chatapp-cc76c.firebaseapp.com',
    storageBucket: 'chatapp-cc76c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM3VVBfxB8M0Lz-t8qovDiedh6sT1DBD4',
    appId: '1:147056837699:android:40fa5c07950f286f8d40f6',
    messagingSenderId: '147056837699',
    projectId: 'chatapp-cc76c',
    storageBucket: 'chatapp-cc76c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1SavpKLCypM5IOu0sKDwQQYeXduipH8',
    appId: '1:147056837699:ios:25f6a31b6d60db358d40f6',
    messagingSenderId: '147056837699',
    projectId: 'chatapp-cc76c',
    storageBucket: 'chatapp-cc76c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1SavpKLCypM5IOu0sKDwQQYeXduipH8',
    appId: '1:147056837699:ios:25f6a31b6d60db358d40f6',
    messagingSenderId: '147056837699',
    projectId: 'chatapp-cc76c',
    storageBucket: 'chatapp-cc76c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHFMkwiEZX8PSBPn-qnF3vwAvhAYhwFoA',
    appId: '1:147056837699:web:c958c37c9d3d3b6e8d40f6',
    messagingSenderId: '147056837699',
    projectId: 'chatapp-cc76c',
    authDomain: 'chatapp-cc76c.firebaseapp.com',
    storageBucket: 'chatapp-cc76c.appspot.com',
  );

}